name: Bangumi Spiderbot

on:
  schedule:
    - cron: "0 0 * * *"   #每天 00:00 UTC
  workflow_dispatch:      #手动触发

jobs:
  run-spider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run spider
        run: python bangumi_spider.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add bangumi.json
          git commit -m "Update bangumi list [skip ci]" || echo "No changes to commit"
          git push
