import requests
from bs4 import BeautifulSoup
import datetime
import json

def fetch_bangumi_list(year: int, month: int):
    url = f"https://youranimes.tw/bangumi/{year}{month:02d}"
    headers = {"User-Agent": "Mozilla/5.0"}
    resp = requests.get(url, headers=headers)
    resp.raise_for_status()
    soup = BeautifulSoup(resp.text, "html.parser")

    result = []

    for h3 in soup.find_all("h3"):
        title = h3.get_text(strip=True)
        bangumi_data = {"标题": title}

        #向下找对应信息
        next_elem = h3.find_next_sibling()
        while next_elem and next_elem.name != "h3":
            if next_elem.name == "p":
                text = next_elem.get_text(strip=True)

                if text.startswith("原作"):
                    bangumi_data["原作"] = text.split("：", 1)[-1].strip()
                elif text.startswith(("總監督", "总监督")):
                    bangumi_data["总监督"] = text.split("：", 1)[-1].strip()
                elif text.startswith("監督") or text.startswith("监督"):
                    bangumi_data["监督"] = text.split("：", 1)[-1].strip()
                elif text.startswith("音樂") or text.startswith("音乐"):
                    bangumi_data["音乐"] = text.split("：", 1)[-1].strip()
                elif text.startswith(("動畫製作", "动画制作")):
                    bangumi_data["动画制作"] = text.split("：", 1)[-1].strip()
                elif text.startswith("原名"):
                    bangumi_data["原名"] = text.split("：", 1)[-1].strip()

            next_elem = next_elem.find_next_sibling()

        if "监督" in bangumi_data and "总监督" not in bangumi_data:
            bangumi_data["总监督"] = bangumi_data["监督"]

        result.append(bangumi_data)

    return result


if __name__ == "__main__":
    now = datetime.datetime.now()
    #修正到季度首月
    month = (now.month - 1) // 3 * 3 + 1
    if month <= 3: month = 1
    elif month <= 6: month = 4
    elif month <= 9: month = 7
    else: month = 10

    data = fetch_bangumi_list(now.year, month)

    #保存JSON
    with open("bangumi.json", "w", encoding="utf-8") as f_json:
        json.dump(data, f_json, ensure_ascii=False, indent=2)

    #保存TXT
    with open("bangumi.txt", "w", encoding="utf-8") as f_txt:
        for bangumi in data:
            f_txt.write(f"《{bangumi['标题']}》\n")
            for field in ["原名", "原作", "总监督", "监督", "音乐", "动画制作"]:
                if field in bangumi:
                    f_txt.write(f"• {field}：{bangumi[field]}\n")
            f_txt.write("\n")

    print(f"已保存 {len(data)} 部番剧信息到 bangumi.json 和 bangumi.txt")
